server:
  port: 8090

management:
  port: 9090
  address: 127.0.0.1

spring:
  h2:
    console:
      enabled: true
  application:
    name: cruncher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bennder.ce6zhzybvz6p.us-west-2.rds.amazonaws.com:5432/bennderdb?currentSchema=backoffice
    username: bennder
    password: bennderti
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        format_sql: true

jwt:
  secret: ej438fu
  expiration: 3200
  header: Authorization